language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

sudo: false

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --colors